camera_window_height: 453
camera_window_width: 1286
camera_window_x: 630
camera_window_y: 31
main_window_height: 166
main_window_width: 522
main_window_x: 91
main_window_y: 42
velodyne_view_pitch: 120
velodyne_view_yaw: -10
velodyne_view_zoom: 0.11999999999999968
velodyne_window_height: 556
velodyne_window_width: 1291
velodyne_window_x: 627
velodyne_window_y: 516
